### ISSUE TITLE
Integration with Local Network

### ISSUE THREAD

**Issue by AAAstorga** [lime-green/remote-docker-aws#25]
Hey, this is an awesome project. I was wondering if you have ever thought of making this work not only with AWS but with a local computer, such as a raspberry pi. Would be awesome to defer all the Docker work to a local machine and not always AWS. The work you've done with syncing is awesome. If this is something you can open to I could always try and tinker with the project and see if I can get it working.

Thanks for the great work!

**Comment by lime-green** [comment]
@AAAstorga Hey Austin, sorry for the delay -- these notifications get easily lost :) 

I would be _very_ interested in that! I was thinking about getting something like that working since I have spare computers that I could potentially use.

Ideally we can break this up into discrete chunks so that it's easy to review and try out. I think it makes sense to refactor `core.py` into two base classes: an "InstanceProvider" class that deals with creating and interacting with instances (cloud or local) and a "RemoteDockerInstance" class that actually does the syncing and tunneling using a given provider object.

Let me know, I would love the help on this local feature!

**Comment by lime-green** [comment]
For the pi in particular, not sure how well this would work since it uses an ARM chip :( I mean, if you're using ARM docker images then it will work fine, but I imagine that is pretty rare.
